server:
  port: 0   # случайный порт для Tomcat (чтобы не конфликтовать с другими сервисами)

spring:
  jpa:
    hibernate:
      ddl-auto: none   # не менять схему БД автоматически
    properties:
      hibernate:
        format_sql: true           # красивое форматирование SQL (но оно не будет выводиться, если уровень OFF)
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: core-users # схема БД
  sql:
    init:
      mode: always    # всегда выполнять schema.sql при запуске
  http:
    logging:
      include-headers: true   # логировать заголовки HTTP (для отладки)
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/ewmdb
    username: user
    password: password

logging:
  level:
    # Уровень логирования пакета (DEBUG — видно логи, INFO — только основные)
    ru.practicum: DEBUG

    # ---- Логи Hibernate (по умолчанию отключены, раскомментируй при необходимости) ----
    # org.hibernate.SQL: DEBUG          # выводит SQL-запросы (значение: DEBUG или OFF)
    # org.hibernate.orm.jdbc.bind: TRACE # выводит параметры запросов (значение: TRACE или OFF)

api:
  log:
    stacktrace: true   # показывать полный stacktrace в ответах ошибок (только для разработки)